import localFont from "next/font/local";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import { ToastContainer } from "react-toastify";

const graphik = localFont({
  src: [
    {
      path: "../assets/fonts/GraphikBold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../assets/fonts/GraphikSemibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../assets/fonts/GraphikMedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/GraphikRegular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/GraphikThin.otf",
      weight: "200",
      style: "normal",
    },
  ],
  variable: "--font-graphik",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${graphik.variable}`}>
        {children}
        <ToastContainer
          position="top-right"
          autoClose={4000}
          hideProgressBar={true}
          newestOnTop={false}
          draggable={false}
          closeOnClick
          pauseOnHover
        />
      </body>
    </html>
  );
}
